### ISSUE TITLE
containerStyle's background color sets the backdrop color instead of the dialog color.

### ISSUE THREAD

**Issue by silencer07** [MaiconGilton/react-native-customisable-alert#1]
given this style:

```
containerStyle: {
    backgroundColor: "red"
  }
```
  
the backdrop color of the modal turns red instead of the alert box color.

**Comment by MaiconGilton** [comment]
Hi, I will check that out and fix asap for you.

**Comment by MaiconGilton** [comment]
@silencer07 Actually that prop is not wrong, the containerStyle props is meant to change the alert wrapper which also wrapps the backdrop, so to avoid misunderstandings I changed containerStyle prop's name to backdropStyle. Also I have not set any prop as for your need (alert box color) so I also create a new global prop called 'alertContainerStyle' so you can set a default alert style for all your alerts.
